### ISSUE TITLE
Things that need to be developed.

### ISSUE THREAD

**Issue by nshaheed** [nshaheed/eecs448_hw4#1]
Classes:
   Book:
      + getCategory() :: String
      + getTitle() :: String
      + getAuthor() :: String
      + getPrice() :: Double
      + setCategory(cat::String) :: String
      + setTitle(ttl::String) :: String
      + get 
      + setPrice( :: Double) :: Double
     ---------------------
      - category::Int
      - title :: String
      - author :: String
      - Price :: Double

   Store Listing:
       +viewCategory(Title::String)
       +getBook(Title::String)
       -books::[Book]

```
Order:
    +addToOrder(Title::String)
    +removeFromOrder(Title::String)
    +getTotal()
    -currentOrder::[Book]
```

**Comment by nshaheed** [comment]
We also need a main file to handle reading the database text file and adding all the read books to the Store Listing class as well as the user interactions.

**Comment by ballesta25** [comment]
I think we hit all this.  Closing.
